### ISSUE TITLE
Bug Report: Images are too big for the buttons

### ISSUE THREAD

**Issue by MissStrong** [BCarlson1512/MavenCSPROJ#4]
![](https://user-images.githubusercontent.com/44328647/51545851-d8701b80-1e30-11e9-9d26-06a3f8eacf53.png)

You can resize the ImageIcon objects so that the images are fully shown on the buttons.

This page be useful: https://stackoverflow.com/questions/2856480/resizing-a-imageicon-in-a-jbutton

**Comment by HiImAlvin** [comment]
fixed.
